#!/usr/bin/python3
# -*- coding: utf-8 -*-
# @Author  : Peihua Tang
# @FileName: 0001_initial.py.py
# @Software: PyCharm

# Generated by Django 2.1.4 on 2019-03-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('place', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('like_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityBelongComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityBelongGroupMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLikeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=120)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FollowMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_left_id', models.IntegerField(default=0)),
                ('user_right_id', models.IntegerField(default=0)),
                ('left_to_right', models.BooleanField(default=False)),
                ('right_to_left', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=40)),
                ('notice', models.CharField(default='未有公告', max_length=240)),
                ('introduction', models.CharField(max_length=240)),
                ('create_time', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(default=0)),
                ('from_id', models.IntegerField(default=0)),
                ('to_id', models.IntegerField(default=0)),
                ('context', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification_type', models.IntegerField(default=0)),
                ('Notification_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(default=0)),
                ('modify_group', models.BooleanField(default=False)),
                ('set_admin', models.BooleanField(default=False)),
                ('send_group_message', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=40)),
                ('access_token', models.CharField(default='0', max_length=100)),
                ('sex', models.IntegerField(default=-1)),
                ('birth', models.DateField(default='')),
                ('phone', models.IntegerField(default=10010)),
                ('status', models.CharField(default='', max_length=100)),
                ('enable_searched', models.BooleanField(default=True)),
                ('enable_visited_list', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttendActivityMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowGroupMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.User')),
            ],
        ),
        migrations.AddField(
            model_name='activitybelonggroupmapping',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Group'),
        ),
        migrations.AddField(
            model_name='activitybelongcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Comment'),
        ),
    ]
